version: '3.8'
services:
  teacher-project:
    image: teacher-project-prod-i
    build: 
      dockerfile: Dockerfile.prod
    container_name: teacher-project-prod-c
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production