FROM node:alpine AS build

WORKDIR /teacher-project

COPY package.json .

RUN npm i

COPY . .

RUN npm run build


FROM nginx

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build /teacher-project/dist /usr/share/nginx/html