export const ROUTES = {
    MAIN: "/",
    LOGIN: "/login",
    TASKS: "/tasks",
    CREATE_USER: "/create-user",
    PROFILE: "/profile",
    TEACHER_SCORES: "/teachers-scores",
    MY_RESULTS: "/my-results",
    SUBMIT_TASK: "/submit-task",
    COMMITTE_TEACHERS: "/committee-teachers",
    ADD_TEACHER: "/add-teacher",
    TEACHER_REQUESTS: "/teacher-requests",
    ALL_USERS: "/all-users",
    TEACHERS: "/teachers",
};
